const ELEMENTS = ['FIRE', 'ELECTRIC', 'METAL', 'COMPUTERY'];
const ACTIONS = ['TURN', 'MOVE', 'ATTACK'];

const CARD_NAMES = {
  FUEL_TANK: 'FUEL TANK',
  BLAZE: 'BLAZE',
  FLAMESPITTER: 'FLAMESPITTER',
  CYCLOTRON: 'CYCLOTRON',
  SPEED: 'SPEED',
  CHAIN_LIGHTNING: 'CHAIN LIGHTNING',
  SCYTHE: 'SCYTHE',
  SKEWER: 'SKEWER',
  RIPSAW: 'RIPSAW',
  MEMORY_CORE: 'MEMORY CORE',
  OMNI_STOMP: 'OMNI STOMP',
  HEXMATIC_AIMBOT: 'HEXMATIC AIMBOT',
};

const CARDS = {
  FUEL_TANK: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  BLAZE: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  FLAMESPITTER: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  CYCLOTRON: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  SPEED: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  CHAIN_LIGHTNING: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  SCYTHE: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  SKEWER: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  RIPSAW: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  MEMORY_CORE: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  OMNI_STOMP: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
  HEXMATIC_AIMBOT: { ACTION: { MOVEMENT: {}, ATTACK: {}, ROTATION: {} }, ELEMENT: '' },
};

const C = { ELEMENTS, ACTIONS, CARD_NAMES, CARDS };

export default C;
